# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d2cucOi1Zvet7DVrhEkN4mBqXcuboJst
"""

import streamlit as st

st.title("a")