# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d2cucOi1Zvet7DVrhEkN4mBqXcuboJst
"""

import streamlit as st

st.title("授業")
st.header("松下莉子")
st.warning("注意")
